name: projecttravelwin
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  # date_time_picker: ^2.1.0
  dio: ^4.0.6
  flutter_custom_clippers: ^2.1.0
  # flutter_neumorphic: ^3.2.0
  flutter_svg: ^1.1.6
  get_storage: ^2.1.1
  http: ^0.13.5
  # intl: any
  getwidget: ^3.1.1
  image_picker: ^0.8.7+4

  image_cropper: ^3.0.2
  file_picker: ^5.2.10
  shared_preferences: ^2.1.0
  contained_tab_bar_view: ^0.8.0

  scrollable_positioned_list: ^0.2.3
  dotted_line: ^3.1.0
  persistent_bottom_nav_bar: ^5.0.2
  web_socket_channel: ^2.4.0
  rxdart: ^0.27.7
  awesome_notifications: any
  #    permission_handler: ^10.2.0
  connectivity_plus: ^4.0.1
  equatable: ^2.0.5
  data_table_2: ^2.4.2
  auto_size_text: ^3.0.0
  flutter_localizations:
    sdk: flutter
  loading_animation_widget: ^1.2.0+4
  desktop_window: ^0.4.0
  permission_handler: ^10.3.0
  url_launcher: ^6.1.11
  syncfusion_flutter_charts: ^21.2.4
  syncfusion_flutter_datagrid: ^21.2.10
  syncfusion_flutter_pdf: ^21.2.4
  google_fonts: ^4.0.4
  flutter_launcher_icons: ^0.13.1
  msix: ^3.14.2
  # fl_chart: ^0.62.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "images/logo.png"
    icon_size: 48
msix_config:
  display_name: Yemen Travel
  publisher_display_name: Yement Travel Team
  identity_name: yementravel.team.com
  msix_version: 1.0.0.0
  logo_path: images/logo.png
  capabilities: internetClient, location, microphone, webcam
  certificate_path: C:\Users\AhmedAlkamel\CERTIFICATEV1.pfx
  certificate_password: vgahmed688

flutter:
  uses-material-design: true
  assets:
    - images/
    - icons/
  fonts:
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
        - asset: fonts/Cairo-Bold.ttf
        - asset: fonts/Cairo-Light.ttf
    - family: AdobeAr
      fonts:
        - asset: fonts/AdobeArabic.ttf
